language: node_js
node_js:
  - "8"

addons:
  apt:
    update: true

script:
  - npm run build

deploy:
  provider: pages
  local-dir: dist/
  skip-cleanup: true
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch:
      - master
      - deploy
